// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase {
    width: 300px;
    height: 300px;

    out property <bool> first-clicked;
    out property <bool> second-pressed;
    out property <bool> second-clicked;

    first := Rectangle {
        x: 0px;
        width: 50%;
    }

    second := Rectangle {
        x: parent.width / 2;
        width: 50%;
    }

    TouchArea {
        clicked => {
            first.background = rgb(255, 0, 0);
            root.first-clicked = true;
        }
    }

    TouchArea {
        event-passthrough: true;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                second.background = rgb(0, 255, 0);
                root.second-pressed = true;
            }
        }
        clicked => {
            // Should not happen
            second-clicked = true;
        }
    }
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;

slint_testing::send_mouse_click(&instance, 5., 5.);
assert(instance.get_first_clicked());
assert(instance.get_second_pressed());
assert(!instance.get_second_clicked());
```

```rust
let instance = TestCase::new().unwrap();

slint_testing::send_mouse_click(&instance, 5., 5.);
assert!(instance.get_first_clicked());
assert!(instance.get_second_pressed());
assert!(!instance.get_second_clicked());
```

```js
var instance = new slint.TestCase();

slintlib.private_api.send_mouse_click(instance, 5., 5.);
assert(instance.first_clicked);
assert(instance.second_pressed);
assert(!instance.second_clicked);
```
*/
